name: backend-prototype-dev

services:
  postgres:
    env_file:
      - .env
  api:
    build:
      target: development
    command: >
      sh -c "npm run db:migrate &&
             npm run dev"

    env_file:
      - .env

    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - node_modules/
            - dist/
            - .git/

        - action: rebuild
          path: package.json

        - action: rebuild
          path: package-lock.json
